---
- name: Reset first master
  hosts: kubic-0, master-except-first, worker
  tasks:
  - name: Reset kubeadm
    command: kubeadm reset --cri-socket="/var/run/crio/crio.sock" --force

- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Clear etcd. Need install etcd locally.
      shell: "ETCDCTL_API=3 etcdctl --endpoints=https://example-client.default.svc:30373  --cert=certs/etcd-client.crt --key=certs/etcd-client.key --cacert=certs/etcd-client-ca.crt del '' --prefix"
